title: Victor Farias - @engvictorfarias# your name (or website title) here
logo: "/images/AVATAR-VICTOR.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, I'm Victor, a Data Scientist Student.
  <br><br>
  He are my projects with Python and R.
  <br><br>
  <a href="https://www.linkedin.com/in/engvictorfarias/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
