title: Victor Farias # your name (or website title) here
logo: "/images/AVATAR-VICTOR.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, I'm Victor, a Data Scientist Student.
  <br><br>
  Here are my projects with Python, R and Power BI.
  <br><br>
  <a href="https://www.linkedin.com/in/eng-victor-farias/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://www.kaggle.com/engvictorfarias">View My Kaggle Profile</a> 
theme: jekyll-theme-minimal
google_analytics: G-MJ0J57DK8K # your Google Analytics tracking ID here
